name: Continuous Deployment

on:
  push:
    branches: ["farhan"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Copy Env
        run: cp .env-copy .env

      - name: Add value to API_KEY
        run: echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env

      - name: Read .env
        run: cat .env

      # - name: Install dependencies
      #   run: yarn install

  #         - name: Build the project
  #           run: yarn build
  #           env:
  #               CI: false

  #         - name: Upload Artifacts
  #           uses: actions/upload-artifact@v2
  #           with:
  #               name: project-build
  #               path: build

  # Deploy:
  #     runs-on: ubuntu-latest
  #     needs: build
  #     steps:
  #         - name: Download Artifacts
  #           uses: actions/download-artifact@v3
  #           with:
  #               name: project-build
  #               path: build
  #         - name: copy file via ssh password
  #           uses: appleboy/scp-action@v0.1.4
  #           with:
  #               host: ${{ secrets.SSH_SERVER_HOST }}
  #               username: ${{ secrets.SSH_USERNAME }}
  #               password: ${{ secrets.SSH_PASSWORD }}
  #               source: 'build/*'
  #               target: /home/almuhtadiaqi/PMS-V3-KEMENLU-FE
